include:
- services/database/tooling/database-compose.yml
- services/migration/tooling/migration-compose.yml
- services/backend/tooling/backend-compose.yml
- services/predict-delays/docker-compose.yaml
volumes:
  db_data:
